# Generated by Django 4.2.10 on 2024-03-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
