# Generated by Django 4.2.10 on 2024-03-12 06:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0006_user_friends_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_request',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
