# Generated by Django 4.2.10 on 2024-03-17 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0007_user_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
