# Generated by Django 4.2.10 on 2024-03-29 05:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0009_conversation_message_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pong_win', models.IntegerField(default=0)),
                ('total_pong_los', models.IntegerField(default=0)),
                ('total_pong_win_tie', models.IntegerField(default=0)),
                ('total_pong_los_tie', models.IntegerField(default=0)),
                ('total_scissors', models.IntegerField(default=0)),
                ('total_paper', models.IntegerField(default=0)),
                ('total_rock', models.IntegerField(default=0)),
                ('total_spr_win', models.IntegerField(default=0)),
                ('total_spr_los', models.IntegerField(default=0)),
                ('total_spr_win_tie', models.IntegerField(default=0)),
                ('total_spr_los_tie', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_count', models.IntegerField(default=0)),
                ('player1_moves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('player2_moves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
