# Generated by Django 4.2.10 on 2024-03-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0010_gamestats_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
