# Generated by Django 4.2.10 on 2024-04-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0011_gamehistory_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFC_Game_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
            ],
        ),
    ]
