# Generated by Django 4.2.10 on 2024-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0012_pfc_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfc_game_id',
            name='room_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
