# Generated by Django 4.2.10 on 2024-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0013_pfc_game_id_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pfc_game_id',
            name='game_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
