# Generated by Django 4.2.10 on 2024-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0014_alter_gamehistory_game_id_alter_pfc_game_id_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='player1_penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2_penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
