# Generated by Django 4.2.10 on 2024-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0015_gamehistory_player1_penalties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_PFC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_in_pong',
            field=models.BooleanField(default=False),
        ),
    ]
