# Generated by Django 4.2.10 on 2024-04-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0016_user_is_in_pfc_user_is_in_pong'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfc_game_id',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_PFC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pfc_game_id',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_PFC', to=settings.AUTH_USER_MODEL),
        ),
    ]
